#!/bin/bash
#
# Copyright (c) 2012-2014 NVIDIA Corporation.  All rights reserved.
#
# NVIDIA Corporation and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA Corporation is strictly prohibited.
#
# Usage: generate_nvtest_ramdisk.sh [target_device]
#        generate_nvtest_ramdisk.sh --help
#
# Description: Generate a ramdisk image suitable for minimal booting of
#              systems without an root file system (such as early development
#              FPGAs systems).
#
# WARNING:  Loading up the ramdisk lots of extraneous files will severely
#           impact the boot time on FPGA systems. The files copied by this
#           script should be kept to the smallest subset possible.
#-------------------------------------------------------------------------------

# Give 'em help if they asked for it.
if [ "$1" == "--help" ]; then
    this_script=`basename $0`
    echo " "
    echo "Generate an Android ramdisk image capable of booting without"
    echo "an external file system."
    echo " "
    echo "Usage:"
    echo " "
    echo "  $this_script [target_device]"
    echo "  $this_script --help"
    echo " "
    echo "where:"
    echo " "
    echo "  target_device: t132 | grenada (default is grenada)"
    echo "  --help:       produces this description"
    echo " "
    exit 0
fi

# Sanity checks & default option processing
if [ "$TOP" == "" ]; then
    echo "ERROR: You must set environment variable TOP to the top of your nvrepo tree"
    exit 2
fi

if [ "$TOP" == "." ]; then
    top=`pwd`
else
    top=$TOP
fi

if [ "$1" == "" -o "$1" == "t210_int" -o "$1" == "t210" ]; then
    echo "Assuming target board is grenada"
    target_device="t210"
else
    target_device=$1
fi

firmware=""
if [ "$target_device" == "t132" ]; then
    firmware="tegra13x"
fi

if [ "$target_device" == "t210" ]; then
    firmware="tegra21x"
fi

if [ "$target_device" == "grenada" ]; then
    firmware="tegra21x"
fi

# Host tools directory
android_host_bin=$ANDROID_HOST_OUT/bin

if [ -d "$OUT" ]; then
    echo "Using $OUT/nvtest_ramdisk_tmpdir to build new ramdisk contents"
    rm -rf $OUT/nvtest_ramdisk_tmpdir
    mkdir -p $OUT/nvtest_ramdisk_tmpdir
else
    echo "ERROR: Product output directory $OUT does not exist"
    exit 2
fi

# Extract the contents of standard ramdisk image generated by JackBuild
if [ -f "$OUT/ramdisk.img" ]; then
    echo "Unpacking archive $OUT/ramdisk.img"
    cd $OUT/nvtest_ramdisk_tmpdir
    gzip -dc < $OUT/ramdisk.img | cpio --extract
else
    echo "ERROR: No ramdisk.img found in $OUT"
    exit 2
fi

#echo "Adding files to $OUT/nvtest_ramdisk_tmpdir/sbin"
#mkdir -p $OUT/nvtest_ramdisk_tmpdir/sbin
#cd $OUT/nvtest_ramdisk_tmpdir/sbin
#cp $OUT/system/bin/nvtest .
#chmod +x ./nvtest

echo "Adding files to $OUT/nvtest_ramdisk_tmpdir/system"
mkdir -p $OUT/nvtest_ramdisk_tmpdir/system
cd $OUT/nvtest_ramdisk_tmpdir/system
cp $OUT/system/build.prop .

echo "Adding files to $OUT/nvtest_ramdisk_tmpdir/system/bin"
mkdir -p $OUT/nvtest_ramdisk_tmpdir/system/bin
cd $OUT/nvtest_ramdisk_tmpdir/system/bin
cp $OUT/system/bin/toolbox .
cp $OUT/system/bin/app_process64 .
#cp $OUT/system/bin/avp_load .

cp $OUT/system/bin/debuggerd64 .
cp $OUT/system/bin/gdbserver64 .
cp $OUT/system/bin/ifconfig .
cp $OUT/system/bin/iftop .
#cp $OUT/system/bin/keystore .
#cp $OUT/system/bin/keystore_cli .
cp $OUT/system/bin/linker64 .
cp $OUT/system/bin/reboot .
cp $OUT/system/bin/logcat .
cp $OUT/system/bin/logwrapper .
cp $OUT/system/bin/mediaserver .
cp $OUT/system/bin/netd .
#cp $OUT/system/bin/netstat .
#cp $OUT/system/bin/newfs_msdos .
#cp $OUT/system/bin/reboot .
#cp $OUT/system/bin/route .
cp $OUT/system/bin/service .
cp $OUT/system/bin/servicemanager .
cp $OUT/system/bin/sh .
cp $OUT/system/bin/surfaceflinger .
#cp $OUT/symbols/system/bin/affinity .

cp -s toolbox cat
cp -s toolbox chmod
cp -s toolbox chown
cp -s toolbox cmp
cp -s toolbox cp
cp -s toolbox date
cp -s toolbox dd
cp -s toolbox df
cp -s toolbox dmesg
cp -s toolbox getevent
cp -s toolbox getprop
cp -s toolbox hd
cp -s toolbox id
cp -s toolbox insmod
cp -s toolbox ioctl
cp -s toolbox kill
cp -s toolbox ln
cp -s toolbox log
cp -s toolbox ls
cp -s toolbox lsmod
cp -s toolbox mkdir
cp -s toolbox mount
cp -s toolbox mv
cp -s toolbox notify
cp -s toolbox printenv
cp -s toolbox ps
cp -s toolbox renice
cp -s toolbox rm
cp -s toolbox rmdir
cp -s toolbox rmmod
cp -s toolbox schedtop
cp -s toolbox sendevent
cp -s toolbox setconsole
cp -s toolbox setprop
cp -s toolbox sleep
cp -s toolbox smd
cp -s toolbox start
cp -s toolbox stop
cp -s toolbox sync
cp -s toolbox top
cp -s toolbox umount
cp -s toolbox vmstat
cp -s toolbox watchprops
cp -s toolbox wipe

if [ "$include_busybox" == "true" ]; then
    # Replace android sh with busybox
    if [ -d $top/busybox-android/ ]; then
        cp $top/busybox-android/busybox .
        for i in `qemu-arm $top/busybox-android/busybox --list`
        do
           rm -rf $i
           ln -sf busybox $i
        done
    fi
fi

if [ "$board_has_wifi" == "true" ]; then
#App for WIFI
echo "Adding app for wifi"
cp $OUT/system/bin/netcfg .
chmod +x ./netcfg
cp $OUT/system/bin/ping .
chmod +x ./ping
cp $OUT/system/bin/ifconfig .
chmod +x ./ifconfig
fi

if [ -d "$OUT/system/vendor" ]; then
    TARGET_COPY_OUT_VENDOR=system/vendor
else
    TARGET_COPY_OUT_VENDOR=vendor
    ln -sf ../vendor $OUT/nvtest_ramdisk_tmpdir/system/vendor
fi

mkdir -p $OUT/nvtest_ramdisk_tmpdir/$TARGET_COPY_OUT_VENDOR/bin
pushd $OUT/nvtest_ramdisk_tmpdir/$TARGET_COPY_OUT_VENDOR/bin

# NVIDIA Test applications
cp $OUT/$TARGET_COPY_OUT_VENDOR/bin/bpmp_sanity .
cp $OUT/$TARGET_COPY_OUT_VENDOR/bin/iova_bpmp_stress .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/bin/nvos_unit .
cp $OUT/$TARGET_COPY_OUT_VENDOR/bin/nvrm_channel .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/bin/nvmap_benchmark .
cp $OUT/$TARGET_COPY_OUT_VENDOR/bin/nvmap_sanity2 .
cp $OUT/$TARGET_COPY_OUT_VENDOR/bin/nvmap_sanity_child2 .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/bin/nvmap_stress .
cp $OUT/$TARGET_COPY_OUT_VENDOR/bin/nvtest .
cp $OUT/$TARGET_COPY_OUT_VENDOR/bin/nvtest64 .
cp $OUT/$TARGET_COPY_OUT_VENDOR/bin/nvmemtest .
cp $OUT/$TARGET_COPY_OUT_VENDOR/bin/reg_dump .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/bin/nvogtest .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/bin/nvogtestgl .
cp $OUT/$TARGET_COPY_OUT_VENDOR/bin/nvgpu_* .
cp $OUT/$TARGET_COPY_OUT_VENDOR/bin/framebuffer_test .
cp $OUT/$TARGET_COPY_OUT_VENDOR/bin/nvrm_unit .
cp $OUT/$TARGET_COPY_OUT_VENDOR/bin/timekeeping_test .
cp $OUT/$TARGET_COPY_OUT_VENDOR/bin/storagesanity .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/bin/tlkstoragedemo_client .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/bin/tlkstoragecmd .
cp $OUT/$TARGET_COPY_OUT_VENDOR/bin/tlk_daemon .
cp $OUT/$TARGET_COPY_OUT_VENDOR/bin/kernel_submit .
cp $OUT/$TARGET_COPY_OUT_VENDOR/bin/lua .
popd

echo "Adding files to $OUT/nvtest_ramdisk_tmpdir/system/etc"
mkdir -p $OUT/nvtest_ramdisk_tmpdir/system/etc
cd $OUT/nvtest_ramdisk_tmpdir/system/etc
#cp $OUT/system/etc/apns-conf.xml .
#cp $OUT/system/etc/dbus.conf .
if [ "$board_has_wifi" == "true" ]; then
echo "adding vram file for wifi"
cp $OUT/system/etc/nvram.txt .
fi

echo "Adding nvogtestgl data files to $OUT/nvtest_ramdisk_tmpdir/data/graphics/nvogtestgl"
mkdir -p $OUT/nvtest_ramdisk_tmpdir/data/graphics/nvogtestgl
cd $OUT/nvtest_ramdisk_tmpdir/data/graphics/nvogtestgl
#cp $OUT/data/graphics/nvogtestgl/* .
cd $OUT/nvtest_ramdisk_tmpdir/data/graphics
#cp $OUT/data/graphics/nvogcrc.txt .

echo "Adding files to $OUT/nvtest_ramdisk_tmpdir/system/etc/firmware"
mkdir -p $OUT/nvtest_ramdisk_tmpdir/system/etc/firmware
pushd $OUT/nvtest_ramdisk_tmpdir/system/etc/firmware
cp -r $OUT/system/etc/firmware/* .
popd

if [ "$board_has_wifi" == "true" ]; then
# wifi firmware files
echo "add setting file for wifi"
mkdir -p $OUT/nvtest_ramdisk_tmpdir/$TARGET_COPY_OUT_VENDOR/firmware
pushd $OUT/nvtest_ramdisk_tmpdir/$TARGET_COPY_OUT_VENDOR/firmware
cp $OUT/$TARGET_COPY_OUT_VENDOR/firmware/fw_bcm4329.bin .
mkdir -p $OUT/nvtest_ramdisk_tmpdir/$TARGET_COPY_OUT_VENDOR
cd $OUT/nvtest_ramdisk_tmpdir/$TARGET_COPY_OUT_VENDOR
mkdir -p $OUT/nvtest_ramdisk_tmpdir/$TARGET_COPY_OUT_VENDOR/firmware
cd $OUT/nvtest_ramdisk_tmpdir/$TARGET_COPY_OUT_VENDOR/firmware
cp $OUT/$TARGET_COPY_OUT_VENDOR/firmware/fw_bcm4329.bin .
popd
fi

#echo "Adding files to $OUT/nvtest_ramdisk_tmpdir/system/etc/security"
#mkdir -p $OUT/nvtest_ramdisk_tmpdir/system/etc
#cd $OUT/nvtest_ramdisk_tmpdir/system/etc/security/etc
#cp $OUT/system/etc/security/otacerts.zip .

echo "Adding files to $OUT/nvtest_ramdisk_tmpdir/system/lib64"
mkdir -p $OUT/nvtest_ramdisk_tmpdir/system/lib64
cd $OUT/nvtest_ramdisk_tmpdir/system/lib64

# Standard libraries
cp $OUT/system/lib64/libc_malloc_debug_leak.so .
cp $OUT/system/lib64/libc.so .
cp $OUT/system/lib64/libcrypto.so .
cp $OUT/system/lib64/libcutils.so .
cp $OUT/system/lib64/libdl.so .
cp $OUT/system/lib64/liblog.so .
cp $OUT/system/lib64/liblogwrap.so .
cp $OUT/system/lib64/libm.so .
cp $OUT/system/lib64/libselinux.so .
cp $OUT/system/lib64/libstdc++.so .
cp $OUT/system/lib64/libutils.so .
cp $OUT/system/lib64/libz.so .
cp $OUT/system/lib64/libgccdemangle.so .
cp $OUT/system/lib64/libselinux.so .
cp $OUT/system/lib64/libsigchain.so .
cp $OUT/system/lib64/libbacktrace.so .
cp $OUT/system/lib64/libunwind.so .
cp $OUT/system/lib64/libunwind-ptrace.so .
cp $OUT/system/lib64/libpcre.so .

# Android libraries
cp $OUT/system/lib64/libbinder.so .
#cp $OUT/system/lib64/libcplconnectclient.so .
cp $OUT/system/lib64/libhardware.so .
cp $OUT/system/lib64/libhardware_legacy.so .
cp $OUT/system/lib64/libnetutils.so .
cp $OUT/system/lib64/libpixelflinger.so .
cp $OUT/system/lib64/libETC1.so .
#cp $OUT/system/lib64/libsurfaceflinger_client.so .
cp $OUT/system/lib64/libui.so .
cp $OUT/system/lib64/libgui.so .
cp $OUT/system/lib64/libmdnssd.so .
cp $OUT/system/lib64/libsync.so .
cp $OUT/system/lib64/libsysutils.so .
cp $OUT/system/lib64/libwpa_client.so .
cp $OUT/system/lib64/libusbhost.so .
cp $OUT/system/lib64/libEGL.so .
cp $OUT/system/lib64/libGLES_trace.so .
cp $OUT/system/lib64/libGLESv2.so .
cp $OUT/system/lib64/libGLESv1_CM.so .

# NVIDIA libraries
mkdir -p $OUT/nvtest_ramdisk_tmpdir/$TARGET_COPY_OUT_VENDOR/lib64
pushd $OUT/nvtest_ramdisk_tmpdir/$TARGET_COPY_OUT_VENDOR/lib64
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvblit.so .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libcgdrv.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvcpl.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvcms.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libglcore.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvglsi.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvddk_2d_v2.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/nvddk2d_rendering_tests.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvddk_vic.so .
if [ ! -z "$video_libs" ]; then
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvmmlite_video.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvmmlite_image.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvtvmr.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvparser.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvmm.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvmmlite.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvmmlite_utils.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvmm_utils.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvfusebypass.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvtnr.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvavp.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvviccrc.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libxmlparser.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/tvmr_compositor_test.so .
fi

#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvddk_aes_user.so .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvddk_audiofx.so .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvddk_audiofx_core.so .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvdispmgr_d.so .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvec.so .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvidia_display_jni.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvgr.so .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvmm_audio.so .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvmm_contentpipe.so .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvmm_image.so .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvmm_manager.so .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvmm_misc.so .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvmm_parser.so .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvmm_service.so .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvmm.so .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvmm_tracklist.so .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvmm_utils.so .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvmm_videorenderer.so .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvmm_writer.so .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvodm_dtvtuner.so .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvodm_hdmi.so .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvodm_imager.so .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvodm_misc.so .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvomxilclient.so .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvomx.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvos.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvrm_graphics.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvrmapi_tegra.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvrm_gpu.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvrm.so .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvsm.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvsurfutil.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvwinsys.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvwsi.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libphs.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libtsec_wrapper.so .

# NVIDIA test libraries
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvapputil.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvtestresults.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/nvddk_vic_tests.so .

if [ ! -z "$video_libs" ]; then
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libnvdc.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/libdisplay_util.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/nvmmlite_videodec_test.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/nvmmlite_videoenc_test.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/nvmmlite_jpegenc_test.so .
fi

#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/nvmm_audioverify_test.so .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/nvwlantest.so .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/omxplayer.so .
#cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/gles2_simplest_lines.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/gles2_simplest.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/liblua.so .
popd

echo "Adding filess to $OUT/system/lib64/modules"
mkdir -p $OUT/nvtest_ramdisk_tmpdir/system/lib64/modules
pushd $OUT/nvtest_ramdisk_tmpdir/system/lib64/modules
cp $OUT/system/lib/modules/iova_tool.ko .
popd

if [ ! -z "$video_libs" ]; then
echo "Adding video data files to $OUT/nvtest_ramdisk_tmpdir/data/video"
mkdir -p $OUT/nvtest_ramdisk_tmpdir/data
cd $OUT/nvtest_ramdisk_tmpdir/data
cp $OUT/video_data/* .
fi

if [ "$board_has_wifi" == "true" ]; then
echo "Adding wifi module to $OUT/system/lib64/modules"
cp $OUT/system/lib64/modules/bcm4329.ko .
fi

echo "Adding files to $OUT/nvtest_ramdisk_tmpdir/system/lib64/egl"
mkdir -p $OUT/nvtest_ramdisk_tmpdir/system/lib64/egl
cd $OUT/nvtest_ramdisk_tmpdir/system/lib64/egl
mkdir -p $OUT/nvtest_ramdisk_tmpdir/$TARGET_COPY_OUT_VENDOR/lib64/egl
cd $OUT/nvtest_ramdisk_tmpdir/$TARGET_COPY_OUT_VENDOR/lib64/egl
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/egl/libEGL_tegra.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/egl/libGLESv2_tegra.so .
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/egl/libGLESv1_CM_tegra.so .
cd $OUT/nvtest_ramdisk_tmpdir/$TARGET_COPY_OUT_VENDOR/lib64

echo "Adding Lua support files"
mkdir -p $OUT/nvtest_ramdisk_tmpdir/$TARGET_COPY_OUT_VENDOR/lib64/lua
mkdir -p $OUT/nvtest_ramdisk_tmpdir/$TARGET_COPY_OUT_VENDOR/lib64/lua/5.1
cd $OUT/nvtest_ramdisk_tmpdir/$TARGET_COPY_OUT_VENDOR/lib64/lua/5.1
cp $OUT/$TARGET_COPY_OUT_VENDOR/lib64/lua/5.1/* .

echo "Adding files to $OUT/nvtest_ramdisk_tmpdir/system/lib64/hw"
mkdir -p $OUT/nvtest_ramdisk_tmpdir/system/lib64/hw
cd $OUT/nvtest_ramdisk_tmpdir/system/lib64/hw
#cp $OUT/system/lib64/hw/gralloc.tegra.so .
#cp $OUT/system/lib64/hw/hwcomposer.tegra.so .


echo "Adding files to $OUT/nvtest_ramdisk_tmpdir/system/xbin"
mkdir -p $OUT/nvtest_ramdisk_tmpdir/system/xbin
cd $OUT/nvtest_ramdisk_tmpdir/system/xbin
#cp $OUT/system/xbin/scp .
cp $OUT/system/xbin/showslab .
#cp $OUT/system/xbin/ssh .
cp $OUT/system/xbin/su .

device_dir=$top/device/nvidia/platform/$target_device
shell_init_rc=$device_dir/init_no_root_device.rc
root_init_rc=$OUT/root/init.rc

if [ -f "$shell_init_rc" ]; then
    echo cp $shell_init_rc $OUT/nvtest_ramdisk_tmpdir/init.rc
    cp $shell_init_rc $OUT/nvtest_ramdisk_tmpdir/init.rc
    echo cp $root_init_rc $OUT/nvtest_ramdisk_tmpdir/init.base.rc
    cp $root_init_rc $OUT/nvtest_ramdisk_tmpdir/init.base.rc
fi

# Package up the new ramdisk image
if [ -d $android_host_bin ]; then
    echo "Packaging new ramdisk contents as $OUT/nvtest_ramdisk.img"
	$android_host_bin/mkbootfs $OUT/nvtest_ramdisk_tmpdir > $OUT/nvtest_ramdisk.img
    echo "Packaging new ramdisk contents as $OUT/fpga_ramdisk.img"
    rm $OUT/nvtest_ramdisk_tmpdir/$TARGET_COPY_OUT_VENDOR/lib64/libglcore.so
	$android_host_bin/mkbootfs $OUT/nvtest_ramdisk_tmpdir > $OUT/fpga_ramdisk.img
else
    echo "ERROR: Host tools directory $android_host_bin does not exist"
    exit 2
fi

echo "Done"
exit 0

